### ISSUE TITLE
v0.1.1 not published on PyPi

### ISSUE THREAD

**Issue by gerbyzation** [ssaavedra/drf-jwt-knox#2]
Thank you for the work on this project! 

Latest version on pypi is 0.1.0, would be great if the latest version could be published there as well.

Also if there's anything you can use contributions on let me know, maybe I can help.

Thanks

**Comment by ssaavedra** [comment]
There is now v0.1.2 published on PyPI which is even more modern than 0.1.1 and should work with both 2.2 and 3.2 LTS Django versions.
